-- CreateEnum
CREATE TYPE "Side" AS ENUM ('RED', 'BLUE');

-- CreateEnum
CREATE TYPE "Status" AS ENUM ('STARTED', 'REMAKE', 'COMPLETED');

-- CreateEnum
CREATE TYPE "Region" AS ENUM ('EUW', 'NA');

-- CreateEnum
CREATE TYPE "Rank" AS ENUM ('IRON', 'BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'DIAMOND', 'MASTER', 'GRANDMASTER', 'CHALLENGER');

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('TOP', 'JUNGLE', 'MID', 'BOT', 'SUPPORT');

-- CreateTable
CREATE TABLE "User" (
    "id" STRING NOT NULL,
    "league_ign" STRING NOT NULL,
    "region" "Region" NOT NULL,
    "rank" "Rank" NOT NULL,
    "main" "Role" NOT NULL,
    "secondary" "Role" NOT NULL,
    "win" INT4 NOT NULL DEFAULT 0,
    "loss" INT4 NOT NULL DEFAULT 0,
    "elo" INT4 NOT NULL DEFAULT 0,
    "external_elo" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Player" (
    "user_id" STRING NOT NULL,
    "scrim_id" INT4 NOT NULL,
    "role" "Role" NOT NULL,
    "side" "Side" NOT NULL,

    CONSTRAINT "Player_pkey" PRIMARY KEY ("user_id","scrim_id")
);

-- CreateTable
CREATE TABLE "Scrim" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "status" "Status" NOT NULL DEFAULT 'STARTED',
    "voice_ids" STRING[],
    "guildID" STRING NOT NULL,
    "region" "Region" NOT NULL,
    "winner" "Side",

    CONSTRAINT "Scrim_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_league_ign_key" ON "User"("league_ign");

-- AddForeignKey
ALTER TABLE "Player" ADD CONSTRAINT "Player_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Player" ADD CONSTRAINT "Player_scrim_id_fkey" FOREIGN KEY ("scrim_id") REFERENCES "Scrim"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
