-- CreateTable
CREATE TABLE "Draft" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "draft_room_id" STRING NOT NULL,
    "bluePicks" STRING[] DEFAULT ARRAY[]::STRING[],
    "redPicks" STRING[] DEFAULT ARRAY[]::STRING[],
    "blueBans" STRING[] DEFAULT ARRAY[]::STRING[],
    "redBans" STRING[] DEFAULT ARRAY[]::STRING[],
    "scrim_id" INT4 NOT NULL,

    CONSTRAINT "Draft_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Draft_scrim_id_key" ON "Draft"("scrim_id");

-- AddForeignKey
ALTER TABLE "Draft" ADD CONSTRAINT "Draft_scrim_id_fkey" FOREIGN KEY ("scrim_id") REFERENCES "Scrim"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
