-- CreateEnum
CREATE TYPE "Team" AS ENUM ('RED', 'BLUE');

-- CreateEnum
CREATE TYPE "Status" AS ENUM ('LOBBY', 'INGAME', 'COMPLETED', 'REMADE');

-- CreateEnum
CREATE TYPE "Server" AS ENUM ('EUW', 'NA');

-- CreateEnum
CREATE TYPE "Rank" AS ENUM ('IRON', 'BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'DIAMOND', 'MASTER', 'GRANDMASTER', 'CHALLENGER');

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('TOP', 'JUNGLE', 'MID', 'BOT', 'SUPPORT');

-- CreateTable
CREATE TABLE "User" (
    "id" STRING NOT NULL,
    "league_ign" STRING NOT NULL,
    "server" "Server" NOT NULL,
    "rank" "Rank" NOT NULL,
    "roles" "Role"[],
    "win" INT4 NOT NULL DEFAULT 0,
    "loss" INT4 NOT NULL DEFAULT 0,
    "elo" INT4 NOT NULL DEFAULT 0,
    "external_elo" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Player" (
    "user_id" STRING NOT NULL,
    "scrim_id" INT4 NOT NULL,
    "role" "Role" NOT NULL,
    "team" "Team" NOT NULL,

    CONSTRAINT "Player_pkey" PRIMARY KEY ("user_id","scrim_id")
);

-- CreateTable
CREATE TABLE "Scrim" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "status" "Status" NOT NULL,
    "voice_ids" STRING[],
    "queue_id" STRING NOT NULL,
    "lobby_creator_id" STRING NOT NULL,

    CONSTRAINT "Scrim_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Queue" (
    "id" STRING NOT NULL,
    "server" STRING NOT NULL,

    CONSTRAINT "Queue_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Queuer" (
    "player_id" STRING NOT NULL,
    "queue_id" STRING NOT NULL,
    "popped" BOOL NOT NULL DEFAULT false,
    "queuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Queuer_pkey" PRIMARY KEY ("player_id","queue_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_league_ign_key" ON "User"("league_ign");

-- CreateIndex
CREATE UNIQUE INDEX "Queue_server_key" ON "Queue"("server");

-- AddForeignKey
ALTER TABLE "Player" ADD CONSTRAINT "Player_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Player" ADD CONSTRAINT "Player_scrim_id_fkey" FOREIGN KEY ("scrim_id") REFERENCES "Scrim"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Scrim" ADD CONSTRAINT "Scrim_lobby_creator_id_fkey" FOREIGN KEY ("lobby_creator_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Scrim" ADD CONSTRAINT "Scrim_queue_id_fkey" FOREIGN KEY ("queue_id") REFERENCES "Queue"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Queuer" ADD CONSTRAINT "Queuer_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Queuer" ADD CONSTRAINT "Queuer_queue_id_fkey" FOREIGN KEY ("queue_id") REFERENCES "Queue"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
